### ISSUE TITLE
CCMN

### ISSUE THREAD

**Issue by olehsamoilenko** [rizky/42-corrections#3]
Hi. I have investigated that you haven't a correction form for CCMN.
I am going to validate this project in one-two weeks and can provide a form.
Please describe format of data you need to make pdf suitable for you.

Have a good day.

**Comment by rizky** [comment]
Hi! sure, PR are welcome. format are not strict as long as contents are readable. I usually follow this step [How to Print to PDF in Firefox, Chrome, IE, Safari](https://pdf.wondershare.com/pdf-knowledge/print-to-pdf-firefox-chrome-ie-safari.html)
